name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          targetDriveId: ${{ secrets.TARGET_DRIVE_ID }}
          templateSpreadsheetId: ${{ secrets.TEMPLATE_SPREADSHEET_ID }}
          data: '[["A1", "A2"], ["B1", "B2"]]'
          columnStartLetter: 'C'
          targetSpreadsheetName: 'Test'

      - name: Print Output
        run: echo "${{ steps.test-action.outputs.spreadsheetId }}"
